package com.myteam2.pro3;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class do1 implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public do1() {
    }




}